WITH RARE AS(
    SELECT ITEM_ID AS RARE_ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
), CURR AS(
    SELECT ITEM_ID AS UPGRADE_ITEM_ID, PARENT_ITEM_ID AS CURR_ITEM_ID
    FROM ITEM_TREE
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT UPGRADE_ITEM_ID
    FROM RARE R JOIN CURR C ON R.RARE_ITEM_ID = C.CURR_ITEM_ID
)
ORDER BY ITEM_ID DESC;